<?php
/**
 * Codifi_Training
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var Codifi\Training\Block\Account\Dashboard\CreditHold $block
 */
//die(var_dump($block->getUrl("Codifi\Training\Controller\Note\Save")));
?>
<?php if ($block->checkForOneTimeDemoMessage()): ?>
    <div class="confirmation-modal-content">
        <p><?= $block->escapeHtml($block->getMessage()) ?></p>
    </div>
    <script>
        require([
            'jquery',
            'Magento_Ui/js/modal/confirm'
        ], function ($) {
            'use strict';

            $('.confirmation-modal-content').confirm({
                actions: {
                    // always: aj();
                    always: function() {
                        $.ajax({
                            type: "POST",
                            url: '<?= $block->escapeJs($block->escapeUrl($block->getSaveUrl())) ?>',
                            data: {'note': 'Customer is notified about credit hold.'},
                            success: function(data){}
                        });
                    }
                },
                buttons: [{
                    text: $.mage.__('OK'),
                    class: 'action primary action-accept',
                    click: function (event) {
                        this.closeModal(event, true);
                    }
                }]
            });
        });
    </script>
<?php endif; ?>
