<?php
/**
 * Codifi_Training
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var Codifi\Training\Block\Account\Dashboard\CreditHold $block
 */
?>
<?php if ($block->check()): ?>
    <div class="confirmation-modal-content">
        <p><?php
            echo $block->getMessage();
            $block->setFlag();
            ?></p>
    </div>
    <script>
        require([
            'jquery',
            'Magento_Ui/js/modal/confirm'
        ], function ($) {
            'use strict';

            $('.confirmation-modal-content').confirm({
                buttons: [{
                    text: $.mage.__('OK'),
                    class: 'action primary action-accept',
                    click: function (event) {
                        this.closeModal(event, true);
                    }
                }]
            });
        });
    </script>
<?php endif; ?>
